### ISSUE TITLE
io.github.EndlessSky.endless-sky is wrong; use io.github.endless_sky.endless_sky instead

### ISSUE THREAD

**Issue by Pointedstick** [flathub/io.github.EndlessSky.endless-sky#2]
Similar to https://github.com/flathub/org.filezillaproject.Filezilla/issues/2

Per https://github.com/ximion/appstream/issues/162#issuecomment-355335480:

> > One such example is FileZilla, which was assigned org.filezillaproject.Filezilla. I gather this is incorrect because filezillaproject != filezilla-project and should have been filezilla_project?
> 
> Yes, Flathub was wrong to apply that transformation. Nobody can own filezilla_project.org because underscores aren't allowed in domain names, so it can't possibly collide with a real domain name, which is why normalizing/escaping filezilla-project to filezilla_project is an OK thing to do. (Similarly, nobody can own _7_zip.org because domain name components can't start with underscores, so it's OK to escape 7-zip as _7_zip, which is the example I like to use in places like the D-Bus Specification.)

Flathub was wrong to use the AppStream ID `io.github.EndlessSky.endless-sky
` for Endless Sky: the hyphens should have been turned into underscores, not removed or left alone.

The correct ID is `io.github.endless_sky.endless_sky`. I have already submitted a patch upstream to correct this in Endless Sky's own AppStream file: https://github.com/endless-sky/endless-sky/pull/3545.

We should do this once we can rename AppStream IDs on Flathub (https://github.com/flathub/flathub/issues/227).

**Comment by TingPing** [comment]
> I know that currently renaming on Flathub is impossible, but I filed this so we don't lose track of the work once that is implemented. By the way, what bug is tracking that work?

I don't believe there is one, feel free to open one on flathub/flathub and reference all these bugs from it.

**Comment by Pointedstick** [comment]
Upstream has merged my patch to use a valid AppStream ID (`io.github.endless_sky.endless_sky`): https://github.com/endless-sky/endless-sky/pull/3545

Now we just need to use that here.

**Comment by bilelmoussaoui** [comment]
This was fixed
