### ISSUE TITLE
cannot install EndlssSky: "Corrupted file object"

### ISSUE THREAD

**Issue by glaubersm** [flathub/io.github.EndlessSky.endless-sky#3]
Hi
I can't install EndlessSky on Arch Linux running flatpak 1.3.3.
Here are the error messages:
```
Erro: Error pulling from repo: Enquanto executava pull de app/io.github.EndlessSky.endless-sky/x86_64/stable a partir do remoto flathub: fsck content object a8ab3597b89ce7f729434208d6c2285ef1cacdaf87db16cf37deda905d504e5a: Corrupted file object; checksum expected='a8ab3597b89ce7f729434208d6c2285ef1cacdaf87db16cf37deda905d504e5a' actual='4dea28a3aaac78942ee275fc61fc3567c214f79e3a4465cb9e90852b5b8bd780'
erro: Falha ao instalar io.github.EndlessSky.endless-sky: Error pulling from repo: Enquanto executava pull de app/io.github.EndlessSky.endless-sky/x86_64/stable a partir do remoto flathub: fsck content object a8ab3597b89ce7f729434208d6c2285ef1cacdaf87db16cf37deda905d504e5a: Corrupted file object; checksum expected='a8ab3597b89ce7f729434208d6c2285ef1cacdaf87db16cf37deda905d504e5a' actual='4dea28a3aaac78942ee275fc61fc3567c214f79e3a4465cb9e90852b5b8bd780'
```

**Comment by corecontingency** [comment]
@glaubersm Are you still having this issue?

**Comment by glaubersm** [comment]
yes, it happened again when I tried to install Endless Sky for the first time on Arch and Neon unstable distros.

`Error: While pulling app/io.github.EndlessSky.endless-sky/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable
error: Failed to install io.github.EndlessSky.endless-sky: While pulling app/io.github.EndlessSky.endless-sky/x86_64/stable from remote flathub: Server returned status 503: Service Unavailable`

Installation was successful after I run `flatpak install flathub io.github.EndlessSky.endless-sky` again.

**Comment by corecontingency** [comment]
@glaubersm This is a [long-standing issue](https://github.com/flathub/flathub/issues/845) with the flathub servers. I have personally encountered this when trying to install several flatpaks.

Luckily, it usually works fine after trying again.
