### ISSUE TITLE
Update to 0.9.10

### ISSUE THREAD

**Issue by Pointedstick** [flathub/io.github.EndlessSky.endless-sky#4]
It was just released. Release announcement and source code: https://github.com/endless-sky/endless-sky/releases/tag/v0.9.9

**Comment by Kirtai** [comment]
The 9.10 _stable_ release is also available at https://github.com/endless-sky/endless-sky/releases/tag/v0.9.10
An update would be nice.

**Comment by corecontingency** [comment]
Closed by pull request #5 . I have also added version 9.11 as an unstable branch.
